input.folder=C://Users//n3299//Desktop//20260201_콘텐트마케터//saram_42
output.folder=out
openai.api.key=
chatgpt.enabled=N
# jobkorea|saramin
resume.format.type=jobkorea

# 파일명에 열거할 키워드
keywords=AI,SNS,캡컷,숏폼

# 파일명에 열거할 키워드
computer.science.terms=마케팅

# Job Description (JD)
job.position=Java 개발
job.responsibilities=- 네이트온/메일/문자 서비스 개발 및 운영 \
- 외부 협력 과제 프로젝트 진행
job.requirements=- Linux 기반 웹 서비스 개발/운영 경험자 \
- Java/JSP, Spring framework, Spring Boot, JPA 활용 서비스 개발/운영 경험자 \
- RDB(Mysql/Oracle) 및 Redis 등 다양한 NoSQL 기술 경험자 \
- 웹서버(apache/nginx), WAS(tomcat/Resin)등에 대한 깊은 이해 및 설치/튜닝 역량 보유자 \
- Restful API 서비스 개발/운영 경험자 \
- Git, Jira, Wiki 등의 협업 도구 사용 경험자 \
- Jenkins 빌드 경험자 \
- Docker 기반 배포 및 Rancher와 같은 컨테이너 관리 플랫폼 활용 경험자 \
- 빌드/테스트/배포 자동화를 통한 CI/CD 경험자
job.preferred=- PHP/BASH/Python 등 스크립트 언어 개발 역량 보유자 \
- 대용량 실시간 데이터 처리 및 아키텍처에 대한 경험자 \
- 웹 프런트엔드 개발 능력과 UI에 대한 기본 지식 및 경험자 \
- 네트워크(HTTP, SSL)에 대한 기본 지식 및 경험자
job.custom=이력서의 적합도 점수를 산정시 아래 조건을 우선하여 산정합니다. \
-나이는 34세에서 43세를 선호하며 44세 이상이라면 스코어에서 감점 \
- 연차는 최소 5년 이상에서 15년 이하로 한정하며 15년 이상이라면 스코어에서 감점 \
- 신입 및 연차 4년 이하는 스코어를 0점 \
- 연봉이 기입되어 있고, 연봉이 7000만원 이상이라면 스코어에서 감점 \
- 프리랜서 경험이 있다면 스코어에서 감점 \
- 연차 대비 잦은 이직은 스코어에서 감점 \
- 컴퓨터관련 학과 전공라면 스코어에서 가산점 
"