# 원본 이력서 경로
input.folder=C://job

# 원본 하위 이력서 폴더의 아래 폴더명 안에 저장
output.folder=out
openai.api.key=
chatgpt.enabled=Y

# 파일명에 열거할 키워드
keywords=ISMS,FW,WAF,IDC,ISO,VPN,ACL,IDS,IPS,DDOS

# 파일명에 열거할 키워드
computer.science.terms=보안

jd="- C/C++/JAVA/PHP 가능 필수 \
- Java, Spring framework, Spring Boot, JPA 활용 서비스 개발/운영 경험자\
- RDB(Mysql, oracle) 및 Redis 등 다양한 NoSQL 기술 경험자\
- 웹서버(apache/nginx), WAS(tomcat, resin)등에 대한 깊은 이해 및 설치/튜닝 역량 보유자\
- Restful API 서비스 개발/운영 경험자\
- 네트워크 프로그래밍 및 시스템프로그램에 대한 깊은 이해\
- Git, Jira, Wiki 등의 협업 도구 사용 경험자\
"